### PR TITLE
~legally distinct~ Nekopad

### PR DESCRIPTION
**Pull request by Neko-22**
i am in the french word for bread :+1: 

Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!
case v7

### CODE REVIEW

**Comment by Neko-22** [comment]
here take this to see my pain in real time
https://github.com/Neko-22/nekopad/commits/main/

**Comment by barxilly** [comment]
image

**Comment by 0CODERKID** [comment]
lol you really utilized your pad by using all the switches :D

**Comment by jpt1729** [comment]
I approve!

[https://github.com/hackclub/hackpad/pull/7](https://github.com/hackclub/hackpad/pull/7)

**Comment by scooterthedev** [comment]
Looks Good! Even though this kinda is closer to a keyboard over a macro pad with the amount of keys lol, I approve!!! 

PS: My Slack Handle is Scooter Y
[onboard](https://github.com/hackclub/OnBoard/pull/531)

**Comment by Neko-22** [comment]
ok finally in a place where i can access my acc
https://github.com/hackclub/hackpad/pull/200#issuecomment-2429311793 is in fact me; i was on mobile at the time w/out access to my laptop or desktop. please dont solder components

**Review by qcoral — APPROVED** [review]
case looks good to me, so you're approved!

fill out this form: https://forms.hackclub.com/hackpad - don't forget to include any screws or heatset inserts you might need!

**Pull request merged**
