### PR TITLE
SpacePad

### PR DESCRIPTION
**Pull request by CodrOfTheFuture**
SpadePad pull request - made a really cool numpad, I hope it gets approved!

### CODE REVIEW

**Comment by pmnlla** [comment]
Heyo! In your STL, you provide a fully assembled model of the macro pad. However, hackclub requires only the case (and plate, if you use one).

**Comment by CodrOfTheFuture** [comment]
> Heyo! In your STL, you provide a fully assembled model of the macro pad. However, hackclub requires only the case (and plate, if you use one).

Yup just made it into two parts (only the case) bottom and top.

**Comment by CodrOfTheFuture** [comment]
> Heyo! In your STL, you provide a fully assembled model of the macro pad. However, hackclub requires only the case (and plate, if you use one).

@pmnlla

**Comment by pmnlla** [comment]
Yeah, I got it.

**Review by qcoral — APPROVED** [review]
hey! I love the front piece, but it's not printable without insane amounts of support - could you try editing it to work differently?

**Comment by sayhan1610** [comment]
Please add a production folder with the gerbers.zip, case folder with individual parts to print in .stl format & the .uf2 firmware file in it. Those were newer requirements I believe and almost everyone has them, it makes it much easier for alex to handle the final job. Also, make sure you followed alex's instructions regarding the printing. Once you're done with that, I'll add my general approval :). You can ping/dm me on slack to lemme know.

**Comment by sayhan1610** [comment]
I approve of this hackpad. The files look all in place. I'm not familiar with kmk but it looks ok to me. Good luck

https://github.com/hackclub/hackpad/pull/64 🦆

**Comment by CodrOfTheFuture** [comment]
sorry could you check again, or someone else, i edited my stl file in production folder called "top layer"

**Review by qcoral — CHANGES_REQUESTED** [review]
hey - love this, but the top case isn't printable - try breaking it up in a different way

**Comment by CodrOfTheFuture** [comment]
changed it, could you look over it again.

**Review by qcoral — APPROVED** [review]
Hey - you might be missing a plate here, but if you're not then its approved!

You can order your hackpad here: https://forms.hackclub.com/hackpad  - make sure to specify the length of screws you need

If you need to update your files, make a new PR and I'll merge it!

**Pull request merged**
