### PR TITLE
hc24 pad

### PR DESCRIPTION
**Pull request by BadPotato1007**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Comment by BadPotato1007** [comment]
lets get this approved!!! 
image
BTW, I want black for the top stl, and white for the bottom one. also, if possible, black keycaps too!

**Review by defihook — COMMENTED** [review]
we can create new pr and merge

**Comment by BadPotato1007** [comment]
Can u not do it for this one?

**Comment by BadPotato1007** [comment]
ok made a new one here https://github.com/hackclub/hackpad/pull/17

**Comment by BadPotato1007** [comment]
@defihook hello??

**Pull request closed without merging**
