### PR TITLE
My little hackpad

### PR DESCRIPTION
**Pull request by Nino678190**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

I hope everything is ok. The firmware will be tested, when the hardware is here.

### CODE REVIEW

**Review by blazecoding2009 — CHANGES_REQUESTED** [review]
Hey @Nino678190 

Can you please put your PCB files into the hackpad directory?

**Comment by Nino678190** [comment]
@blazecoding2009 what do you mean. The hole hackpad files or just change the directory name of the PCB?

**Comment by blazecoding2009** [comment]
All of your hackpad files need to be moved into a separate directory.

**Comment by Nino678190** [comment]
> All of your hackpad files need to be moved into a separate directory.

Do I need to paste all other files in there or is this optional?

**Comment by blazecoding2009** [comment]
Yes, can you undelete the files which were not from your hsckpad?

**Comment by Nino678190** [comment]
I clone the Repo and copy the files in. Give me a bit time

**Comment by Nino678190** [comment]
@blazecoding2009 Should be ok?

**Comment by M0HID** [comment]
Hey! Could you remake this PR please? Right now it's affecting the entire repo and I can't review it. If you have any questions DM me on slack @m0.hid

**Pull request closed without merging**
