### PR TITLE
Fix typo (learm -> learn)

### PR DESCRIPTION
**Pull request by garyhtou**
I love this YSWS! Just found a typo on the home page.

### CODE REVIEW

**Comment by kavishdevar** [comment]
Hah, I was just about to create a PR, and saw this :]

**Review by defihook — COMMENTED** [review]
what was your typo exactly?
I cant recognize btw

**Comment by kavishdevar** [comment]
"learm" to "learn"

**Review by kavishdevar — APPROVED** [review]

**Comment by garyhtou** [comment]
> btw, should everyone be allowed to review?

On GitHub, usually, anyone can leave a review to provide feedback. If a repo owner chooses, they can configure the repo settings so that reviews are required before merge, and only certain people's reviews count towards that requirement.

**Pull request merged**
