### PR TITLE
DKHackpad

### PR DESCRIPTION
**Pull request by KhawZhenXuan**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Your case should be split in 2 parts so you can assemble everything, and please provide a gerber file!

**Comment by KhawZhenXuan** [comment]
> Hey! Your case should be split in 2 parts so you can assemble everything, and please provide a gerber file!

would it be ok if I put it in .stl file?

**Comment by KhawZhenXuan** [comment]
> Hey! Your case should be split in 2 parts so you can assemble everything, and please provide a gerber file!

Done! and Thank you

**Comment by Dongathan-Jong** [comment]
Looks good to me! Get your hackpad here: https://forms.hackclub.com/hackpad

**Comment by KhawZhenXuan** [comment]
> Looks good to me! Get your hackpad here: https://forms.hackclub.com/hackpad

maximum 5 gerber files only, which one do i need to upload?

**Pull request merged**
