### PR TITLE
Add cyaopad

### PR DESCRIPTION
**Pull request by cheyao**
Hello!

I'm happy to be the first person who submits a ship pr to the repo :D 

It's my first time making a PCB, so the board is quite simple, you can find pics of it in the readme. I've designed it all from scratch :P

I'm not quite sure if I should make my project a submodule or copy everything here. Let me know if there is any problems.

Thanks!

### CODE REVIEW

**Comment by cheyao** [comment]
If it is possible, can I get a light blue case? Like this color:
Screenshot 2024-09-19 at 9 23 10 PM

**Comment by cheyao** [comment]
Yay finished adding LCD! Hope everything works fine.

**Comment by cheyao** [comment]
By the way, can the cover be an acrylic board please?

**Comment by cheyao** [comment]
I've added a interactive BOM at `hackpads/cyaopad/PCB/production/ibom.html` to improve the experience of PCBAlex ❤️

**Review by defihook — COMMENTED** [review]
to the moon

**Comment by cheyao** [comment]
Wdym @defihook ?

**Comment by qcoral** [comment]
Hey!! Thanks for being one of the early submissions, PR review is finally starting!! There's been some updated submission guidelines since though, so if you could please update your PR according to https://hackpad.hackclub.com/submitting that would be great! I'll come back around soon

**Comment by cheyao** [comment]
Hey! Thanks for the comment, I've reviewed the requirements according the site and updated my pr, can you check if it is ok? Thanks!

**Comment by qcoral** [comment]
STL import seems to have your pcb + parts in it 
image

**Comment by cheyao** [comment]
image
Didn't the site say it should include the pcb?

**Comment by qcoral** [comment]
Check the "creating production files" section of the guide https://hackpad.hackclub.com/submitting

**Comment by cheyao** [comment]
Ok! I just removed the PCB

**Comment by qcoral** [comment]
The case is still one part, if I were to 3D print it you'd have no way of assembling it - could you break it up into multiple parts?

**Comment by cheyao** [comment]
Hey alex! I've finally managed to separate the case and the top - ran into a lot of problems lol (dependencies, CPU is not enough to handle the workload etc.).

**Review by qcoral — APPROVED** [review]
Nice work on all the changes! Congrats on getting approved for parts, you can order them here:
https://forms.hackclub.com/hackpad

**Comment by cheyao** [comment]
Thank you! :heart:

**Review by qcoral — APPROVED** [review]
Nice job on all the changes!! This has been approved, you can order your hackpad here:
https://forms.hackclub.com/hackpad

**Pull request merged**
