### PR TITLE
0xBB

### PR DESCRIPTION
**Pull request by BoomBoomMushroom**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Comment by BoomBoomMushroom** [comment]
> add binary

Alright I'll do it when I get home, should I reopen the pull request or just let you know?

**Comment by BoomBoomMushroom** [comment]
> add binary

How do I compile kmk?
Isn't kmk's python the firmware already?

**Review by qcoral — APPROVED** [review]
Nice job on this! I love the logo on the macropad. Consider this approved

When you send in the order form, please make sure you add what screws you need! Other than that, looks good to go.

https://forms.hackclub.com/hackpad

**Pull request merged**
