### PR TITLE
tim12 HACKPAD submission

### PR DESCRIPTION
**Pull request by timwhat**
Just finished my HACKPAD and I am submitting

### CODE REVIEW

**Comment by opott** [comment]
Hi,
You don't seem to have a folder with your KiCad project files for your PCB. Please could you upload this?

**Comment by timwhat** [comment]
> Hi, You don't seem to have a folder with your KiCad project files for your PCB. Please could you upload this?

Oh I have the Gerbers.zip there, but if its still required I can upload them tonight

**Comment by opott** [comment]
I'm pretty sure we still require all of the KiCad files to review them!

**Comment by timwhat** [comment]
Alright, I'll upload them when I get home, Just to make sure, just the schematic and PCB file

**Comment by pmnlla** [comment]
For your screw holes, are you going to be using threaded inserts? If so, you'll want to replace them with slightly bigger pilot holes. Otherwise, you're good to go on that end.

**Comment by pmnlla** [comment]
For self tapping screws, you can 100% do that. But I recommend you add a
small chamfer on the exposed side of the hole so the screw fits in easier.
Not something I'd recommend, and not all screws are self tapping. I like
standard flat hex screws like these, but you've probably got a different
idea than me.

**Comment by timwhat** [comment]
Ohhh so it also guides the screw, like this? Also I feel as though the small start of the thread on the screw would be enough to tap
image
image

**Comment by pmnlla** [comment]
That specific kind does _not_ self tap. You want a set of pointy ones that are explicitly marketed to self tap.

**Comment by timwhat** [comment]
Are you sure as I've tried this before and it has worked out pretty well with a 3D print and a M3 screw, also shown in this reddit post https://www.reddit.com/r/3Dprinting/comments/183jy1q/i_made_a_screw_fit_guide_following_a_suggestion/
image

**Review by qcoral — APPROVED** [review]
awesome job on your hackpad! can't wait to see how the gaskets turn out

fill out this form to order: https://forms.hackclub.com/hackpad

have fun!!

**Pull request merged**
