### PR TITLE
Aksharashackpadresubmit (this is a resubmit, the first one had the wrong formatting and wasn't mergeable, sorry about the timing)

### PR DESCRIPTION
**Pull request by AksharaK12**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Looks good to me! @Hyatt B.

**Comment by M0HID** [comment]
Also please provide your source KiCad files!

**Comment by Sycrosity** [comment]
The firmware should also be in UF2 format 😉

**Comment by AksharaK12** [comment]
Just added the pcb source files, but for firmware I decided to switch to kmk because qmk wasn't compiling so it's a py file that I'll eventually put directly on the mcu, hope that's ok

**Review by M0HID — CHANGES_REQUESTED** [review]
Great work, but in your schematic the row should not be directly connected to ground, because you have a Matrix, the common connection will make it so that the Xiao is unable to differentiate between keys. Could you remove that please and update the PR?

**Comment by AksharaK12** [comment]
Just got rid of that gnd in my shematic (and the connection to it in the pcb), will it work now? ty for pointing out the error

**Review by M0HID — COMMENTED** [review]
Nice work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
