### PR TITLE
added another useful resource to the readme :)

### PR DESCRIPTION
**Pull request by v1peridae**
edit to avoid confusion: adding resources that could help

### CODE REVIEW

**Comment by V205Arduino** [comment]
What about the location of the folder(eg projects folder), and the title?

**Comment by v1peridae** [comment]
hi! i'm submitting a resource that could help ppl making their own hackpads, not my own project submission :')

**Comment by V205Arduino** [comment]
Oh oops, sorry for confusion.

**Review by defihook — COMMENTED** [review]
new youtube video

**Comment by qcoral** [comment]
Hey! Thanks for adding the resources. Totally should've merged this earlier - that on me. Feel free to add these to the website in a new PR, going to be closing this for now!

**Pull request closed without merging**
