### PR TITLE
Davepadv1

### PR DESCRIPTION
**Pull request by AlphaBeta42**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
great progress

**Review by qcoral — CHANGES_REQUESTED** [review]
This is absolutely amazing, but I'm having a little trouble seeing how it's all supposed to fit together phyiscally - there doesn't seem to be any screw holes in the PCB. If you could draw a diagram or something (even ms paint works) and attach it here that'd be great!

**Comment by AlphaBeta42** [comment]
Submitted the wrong version pcb file lol. I _had_ put in screw holes, then I removed LEDs and must've removed screw holes at the same time by mistake.
Amended to include holes to match the case base plate. I intend to use spacer screws (which I can provide) to mount it.
image

**Comment by qcoral** [comment]
Glad we caught this - consider it approved!! 

You can order your hackpad here: https://forms.hackclub.com/hackpad

**Review by defihook — COMMENTED** [review]
davepad

**Pull request merged**
