### PR TITLE
WillPad

### PR DESCRIPTION
**Pull request by WilliamBSITT**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Comment by Dongathan-Jong** [comment]
Hey! You seem to have uploaded the whole cad model to the PR, please upload the case to the folder! Also, I see that you haven't requested screws, add them to the BOM!

**Comment by WilliamBSITT** [comment]
Hi, I add the STL and update the BOM, but for the screw or the spacer, if you don't have it, I already have it, that's why I didn't put it in the BOM at first.

**Review by qcoral — CHANGES_REQUESTED** [review]
I can't seem to get the gerber files to work - can you test it on the jlc website and let me know?

**Comment by WilliamBSITT** [comment]
Yes sure I look when I m home

**Comment by WilliamBSITT** [comment]
So, I just look and it work perfectly
image

**Review by qcoral — APPROVED** [review]
Must've been a weird issue on my end - congrats, you can get your hackpad ordered here:

https://forms.hackclub.com/hackpad

**Pull request merged**
