### PR TITLE
Briyan's SwiftPad!

### PR DESCRIPTION
**Pull request by briyandyju09**
Introducing Swift! My macropad that will hopefully make me productive.

The files are as follows:

├── CAD \
│   ├── (TOP CASE).stl \
│   └── (BOTTOM CASE).stl \
├── firmware \
│   └── code.py \
└── PCB \
    ├── (GERBER).zip \
    └── BOM & Schematic

### CODE REVIEW

**Comment by briyandyju09** [comment]
PS: ill be soldering everything myself to not trouble the PCBAlex service alot 😉
PS: Black case if possible plss! and a black PCB!

**Review by defihook — COMMENTED** [review]
what is new update?

**Comment by briyandyju09** [comment]
@defihook I made a slight change to the firmware =)

**Review by defihook — COMMENTED** [review]
confirmed

**Review by defihook — COMMENTED** [review]
make sense
great work

**Review by qcoral — APPROVED** [review]
This all looks good to go! Congrats on being the first PR to be approved, can't wait to see it in action. You can order your hackpad here:

https://forms.hackclub.com/hackpad

**Pull request merged**
