### PR TITLE
SimController

### PR DESCRIPTION
**Pull request by opott**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by opott** [comment]
Oh no, has the pull bot reverted everything 😢

**Comment by qcoral** [comment]
wait hold on what happened here

**Comment by opott** [comment]
This has happened before 🤦‍♂️

**Comment by opott** [comment]
I need to figure out how to get rid of this pull bot

**Comment by qcoral** [comment]
good luck; you can make a new pr once you figure out how to fix it

**Comment by opott** [comment]
Ive just re-submitted my PR (https://github.com/hackclub/hackpad/pull/252)
sorry about this! @qcoral

**Pull request merged**
