### PR TITLE
Jun

### PR DESCRIPTION
**Pull request by junhong27**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by MrDomocle** [comment]
I approve
My PR: https://github.com/hackclub/hackpad/pull/80

**Comment by Hyatt-B** [comment]
Looks good! @HyattB.

**Comment by Sycrosity** [comment]
How is your board held up? It seems as though the board would not hold up on it's own - unless it's held up by the switches and the acrylic plate, but that would make it not super stable.
image

**Comment by Sycrosity** [comment]
Also, the rotary encoder they have at HQ has pins for a button! You don't seem to be using these pins or the cutout which has them, which is fine, except you are losing an extra input you could have :)

**Comment by Sycrosity** [comment]
You have also not accounted for the height of the header pins on the RP2040, so either have to fix this or just cut/drill it out yourself. See here: [link](https://hackclub.slack.com/archives/C07LESGH0B0/p1729723591668939)

So I think this will need a few more changes before it's ready to ship, unfortunately!

image
image
image

**Review by qcoral — APPROVED** [review]
Hey! Love this - there'll be a few SMD xiaos and I can ship that to you, just please let me know in the order form that you need one

https://forms.hackclub.com/hackpad

**Pull request merged**
