### PR TITLE
ForgePad

### PR DESCRIPTION
**Pull request by tonystdeng**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

What was your inspiration to make it?
from this guy called ScottpadV1's product, but without the spining input thing(i don't know how to make it) and more buttons(because i can lol)

Hardest challenges faced
don't know anything about it(case making, qmk, wiring, literaly everything)

Other fun facts to know
i spend 5 hours learning how to upload [ai03's plate generator](https://kbplate.ai03.com/)'s product onto my top case in blender

Every hackpad submission's page will be published on the main hackpad website, so make sure to go submit!

I KNOW IT'S LATE BUT PLEASE ALLOW I'M BEGGING

### CODE REVIEW

**Comment by jpt1729** [comment]
Could you please put your PCB files for your PCB in a folder called "PCB"?

**Comment by tonystdeng** [comment]
image
i also changed the cad to upper just in case, let me know if anything else is wrong

**Review by jpt1729 — CHANGES_REQUESTED** [review]
Some small changes

- [ ] In your production folder separate the top and bottom of your case into two files
- [ ] For your PCB, switch your XIAO RP2040 to the through-hole model!

**Review by jpt1729 — APPROVED** [review]
LGTM

https://github.com/hackclub/hackpad/pull/7

**Review by M0HID — APPROVED** [review]
Looks great! Remember to add any screws in your BOM if you need them. You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
