### PR TITLE
update cad and bom

### PR DESCRIPTION
**Pull request by polypixeldev**
Just updating the CAD and BOM for my hackpad!

### CODE REVIEW

**Review by a3acx — COMMENTED** [review]
Looks good except I don't see any firmware.
-@a3acx

**Comment by polypixeldev** [comment]
The firmware was in my first PR that already got approved and merged, this is just updating my CAD

**Comment by a3acx** [comment]
Ok. My bad. CAD looks good though.

**Comment by qcoral** [comment]
LGTM

**Pull request merged**
