### PR TITLE
Added HexPad

### PR DESCRIPTION
**Pull request by atharva-malik**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Sycrosity** [comment]
The firmare needs to be in uf2 format: [link](https://arc.net/l/quote/nfmsuvnk)

**Comment by atharva-malik** [comment]
> The firmare needs to be in uf2 format: [link](https://arc.net/l/quote/nfmsuvnk)

The firmware is written with KMK, which is flashed as a code.py file as can be seen in it's documentation here, therefore it is not as a uf2. See the steps here for more info: [KMK Getting Started](https://github.com/KMKfw/kmk_firmware/blob/main/docs/en/Getting_Started.md)

**Comment by Sycrosity** [comment]
except you have to convert it to uf2 format, otherwise they cannot download the firmware onto your board

**Comment by Sycrosity** [comment]
yup completely right mb!

**Review by qcoral — APPROVED** [review]
nice job on this hackpad! a little unsure if there'll be enough clearance for the xiao since it hangs off the edge of the pcb, but that's okay - you can make a new PR to make changes if this is a problem for you

Regardless, you've been approved! Fill out the form here: https://forms.hackclub.com/hackpad

**Pull request merged**
