### PR TITLE
spypad

### PR DESCRIPTION
**Pull request by DefinitelyInconspicous**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Comment by DefinitelyInconspicous** [comment]
*There are some comments in the code because I put it through chatgpt to explain how to do some stuff, then it just commented everything

**Review by defihook — COMMENTED** [review]
add binary

**Comment by DefinitelyInconspicous** [comment]
Hi - What do you mean by Add Binary?

**Review by qcoral — CHANGES_REQUESTED** [review]
This is awesome! I love the decals. A couple things:

- The macropad needs to go into the hackpads folder, seems like the directory structure is a little messed up. I can fix it if you can't figure it out
- The case is in a ZIP, I need a .STEP file

good luck!

**Comment by DefinitelyInconspicous** [comment]
Hi,

There’s a .step file inside the .zip file. I can’t upload the raw step
because it’s too big.

**Comment by DefinitelyInconspicous** [comment]
Sry I accidentally closed it, Im not very experienced in prs lol. I fixed the directory issue but Im not sure if I can do anything about the .step file.

**Review by qcoral — CHANGES_REQUESTED** [review]
If you remove the PCB 3D model would it decrease the size of the step? if so, try doing that!

**Comment by DefinitelyInconspicous** [comment]
Ok it worked :) [By the way in the cad there's an assembled version of the macropad, don't print that :D]

**Review by qcoral — APPROVED** [review]
nice job sorting this out, I love all the decals, consider this approved:

https://forms.hackclub.com/hackpad - make sure to specify the length of screws you need!

**Pull request merged**
