### PR TITLE
Add the tabbyhack K4!!!

### PR DESCRIPTION
**Pull request by FluxC0**

### CODE REVIEW

**Comment by scooterthedev** [comment]
Hey @FluxC0!

After I and Scott reviewed your PCB we just have a few comments to make before I can give my approval.

1. Since you have less than 5 switches, I think it would be better to wire they all directly
2. You should change your RP2040 footprint to a hole-through component if you want it to be soldered as right now it is an SMD component, and you would have to solder that yourself.

Besides for that, the rest of the PCB looks good!

PS: My Slack Handle is Scooter Y

**Comment by scooterthedev** [comment]
Regarding your case, it looks good to me 👍. Good job on that, I give my approval!

PS: My Slack Handle is Scooter Y

**Comment by FluxC0** [comment]
Hey! thanks for the review! you are awesome! as for the switches, i have a pretty good explanation.
it used to have more going on, but i converted to the current design last minute, and didnt want to prod around with rewriting everything.

I'll switch that footprint over when i can.

**Comment by FluxC0** [comment]
or, i'll just leave it as is and solder the xiao on myself. if that would work? would the rest be soldered still?

**Comment by scooterthedev** [comment]
> Hey! thanks for the review! you are awesome! as for the switches, i have a pretty good explanation.
> it used to have more going on, but i converted to the current design last minute, and didnt want to prod around with rewriting everything.

That's fine, just making sure you know that that is happening!
> I'll switch that footprint over when i can.

Yah, that would be good. I think it's better to convert it to a through-hole component so it would be easier to solder. Soldering SMD's can get tricky if your not that well versed in that area. All the other components should be soldered by Alex since they are through-hole.

**Comment by M0HID** [comment]
Hi! Great work so far, but as said above, the footprint needs to be changed to the THT one if you want it soldered by PCBAlex. The rest looks fine though!

**Comment by qcoral** [comment]
Just to burn through PR's I'll approve this for now - don't worry about the parts, they'll be soldered

https://forms.hackclub.com/hackpad

**Pull request merged**
