### PR TITLE
Coder Kid's Hackpad 

### PR DESCRIPTION
**Pull request by 0CODERKID**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by cheyao** [comment]
Hello! 

Please rename the directories to the required names, for example `My PCB` to `PCB. And please remove the spaces in the file names, it's kinda frustrating to type names with spaces in the terminal.

The step file should belong in it's own folder named `CAD`

The PCB is ok. No big problems.

The firmware looks copy-pasted, you still got example username and yourwebsite.com there, and some wierd python code? I think you should modify it to be a bit less template-y. 

Anyways I'll approve after you make some changes.

**Comment by 0CODERKID** [comment]
Hi , i renamed the name from 'MY PCB' to 'PCB' , Also I can't find any spaces in any files name 
 .. and the entire code is written by me .. not copied it from anywhere
 
 Also i didn't understood wdym by  "  you still got example username and yourwebsite.com there? I think you should modify it to be a bit less template-y. "

**Comment by 0CODERKID** [comment]
And yea , I'm really struggling with the case .. i asked from alex to give me a week more .. and he approved me , so can you pls wait wait for some more time? and pls send you're slack username so i can inform you whether my pr is fully done or not

**Comment by cheyao** [comment]
You see here:
image
There are links like `C:\\Users\\YourUsername` and `https://yourwebsite.com`, which are common in tutorials, thus I thought that you directly copied the code. Sorry if I'm mistaken. But you should probably modify this to something that is more your own.

Here you see, there are spaces in the file names, but just leave it so. It is just a tiny nuisance.
image

My slack is @cyao feel free to ping me when you are dome :D

**Review by cheyao — CHANGES_REQUESTED** [review]
Uh hate to say it but you are using the wrong footprint for the xiao. See in your pcb vcc is in the bottom right
image
But it should be in the top right
image
So your row 2 is currently connected to 5V

You should also change the xiao schematic to a more accurate one. (Download it from the OPL lib)

In the CAD your USB hole isn't a hole
image

And what are these holes for? You will have a PCB in the middle without holes so you can't put screws in them
image

**Comment by 0CODERKID** [comment]
Did all the changes!

**Comment by souptik-samanta** [comment]
I approve #85

**Comment by souptik-samanta** [comment]
I approve #85

**Review by souptik-samanta — CHANGES_REQUESTED** [review]
please remove the 7)
" All the components are through-hole "

**Comment by 0CODERKID** [comment]
> please remove the 7) "All the components are through-hole " : )

Done

**Review by souptik-samanta — APPROVED** [review]
I approve #85

**Comment by shim-sham** [comment]
I approve #181

**Review by jpt1729 — APPROVED** [review]
LGTM

https://github.com/hackclub/hackpad/pull/7

**Comment by cheyao** [comment]
LGTM #4

**Review by cheyao — APPROVED** [review]

**Comment by invictus-anic3tus** [comment]
I approve #92
very nice looking

**Comment by qcoral** [comment]
damn y'all 😭

**Pull request merged**
