### PR TITLE
qwel's hackpad

### PR DESCRIPTION
**Pull request by qwel-exe**
had an amazing time building this :)

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Great work, but the case needs a little work! The hole for the port is a little off and too small!

**Comment by qwel-exe** [comment]
Have updated the case but for some reason not able to export as .step can you check once

**Comment by Dongathan-Jong** [comment]
Alright, great job! I see you haven't requested screws in your BOM, if you would like them, there is a box for you to fill out on the form. Get your hackpad here: https://forms.hackclub.com/hackpad

**Comment by qwel-exe** [comment]
🚀

**Pull request merged**
