### PR TITLE
Shambhavi's MIDI hackpad

### PR DESCRIPTION
**Pull request by shim-sham**

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Do you have a top for this case? I see screw holes, but no screw holes on the PCB. Also, you can request screws in the BOM!

**Comment by shim-sham** [comment]
hi! i don't have a top for the case, the pcb will just slot in

**Review by souptik-samanta — CHANGES_REQUESTED** [review]
Need to add files in prodction if qmk : the .uf2 files 
if kmk then boot.py and code/main.py
also could you add you pcb in the ..CAD/case.step file ?
image
something like this with add parts at their place 

without that everything looks great do that and ping me in slack @souptik-samanta 
I will surely approve !!

**Review by souptik-samanta — APPROVED** [review]

**Review by souptik-samanta — APPROVED** [review]

**Comment by shim-sham** [comment]
done... hopefully

**Comment by souptik-samanta** [comment]
I approve #85

**Review by M0HID — APPROVED** [review]
Love your design! You can go ahead and order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
