### PR TITLE
Capslock Light ++

### PR DESCRIPTION
**Pull request by UnnaturalTwilight**
I think I have everything here, I will update if I find any problems.
My hackpad uses only THT components, there are pads on it that the leads of WS2812b tape could be soldered to but the current case design doesn't have room for this, nor do I have intentions of using this short-term, but I wanted to include the option for upgrading in the future. 
I am interested in doing the write-up on the project but probably don't have time to until after the deadline.

image

### CODE REVIEW

**Review by UnnaturalTwilight — COMMENTED** [review]
Ok, I think Im done

**Comment by UnnaturalTwilight** [comment]
Updated
There is currently 2 drill files in gerbers.zip because I didn't know the format I should use
The changes to .gitignore are really only necessary on my fork but I don't know how to exclude a file from a pull request

**Comment by UnnaturalTwilight** [comment]
And Done!
If it would help with assembly I can share an onshape link to my design privately, as I do not want to share my last name publicly

**Comment by M0HID** [comment]
Great job! Could you separate each individual part of your case into their own files please? [(as per the submission guidlines)](https://hackpad.hackclub.com/submitting#:~:text=Each%20individual%20part%20of%20the%20case%20should%20be%20exported%20into%20its%20respective%20files%3A)

**Comment by UnnaturalTwilight** [comment]
I do have them separate in production/case/ as .step files since most slicers can open them and they result in higher quality prints over .stl

**Review by qcoral — APPROVED** [review]
Insanely good PR, nice work. You can get your hackpad by filling out this form:

https://forms.hackclub.com/hackpad

**Pull request merged**
