### PR TITLE
JolynnDuckHackPad

### PR DESCRIPTION
**Pull request by j0lynN-Y**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by M0HID — CHANGES_REQUESTED** [review]
Hi there, great work on this, but your files are in the wrong folder! They should be in the hackpads/JolynnDuckHackpad folder. If you could move them and update the PR that would be great!

**Review by qcoral — CHANGES_REQUESTED** [review]
This is great, but there seems to be 2 macropads - what's going on?

**Comment by qcoral** [comment]
Update - looks like an error on our end, you're fine

**Review by qcoral — CHANGES_REQUESTED** [review]
Regardless, I need the source kicad files for this! Let me know when you've added them

**Comment by j0lynN-Y** [comment]
> Regardless, I need the source kicad files for this! Let me know when you've added them

Hi ive added the source kicad files

**Review by M0HID — CHANGES_REQUESTED** [review]
Hey - I'm a little confused as to how this would print, it looks like it has a floating edge, and it sticks out at the bottom. Is this intentional? If not could you fix please

image
image

**Comment by j0lynN-Y** [comment]
> Hey - I'm a little confused as to how this would print, it looks like it has a floating edge, and it sticks out at the bottom. Is this intentional? If not could you fix please
> 
> image image

helloo, sorry about that, i have no idea how to remove that floating edge so i just redid it, just reuploaded the file, thank you!

**Review by M0HID — APPROVED** [review]
Nice work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
