### PR TITLE
Meddy Ben Ayed

### PR DESCRIPTION
**Pull request by stygmatic**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Comment by Dongathan-Jong** [comment]
Hey! Everything looks good, please make a folder in the folder hackpads, and put all your files in a new folder called 'Mbena1'. The folder should be inside the folder containing the orpheuspad.

**Review by a3acx — COMMENTED** [review]
Looks good to me!
-@a3acx

**Review by qcoral — CHANGES_REQUESTED** [review]
hey - the GND and VCC pins of your oled are flipped!

**Review by stygmatic — COMMENTED** [review]
switched GND and VCC pins so that oled is wired correctly

**Review by stygmatic — COMMENTED** [review]
fixed oled changes :)

**Review by defihook — COMMENTED** [review]
done

**Review by M0HID — CHANGES_REQUESTED** [review]
Hey there! Great work on this, but could you add a README containing your BOM, as wellas your gerber files to a production/ folder? I'll be able to review it once you've done that.

**Review by stygmatic — COMMENTED** [review]
added readme and placement files :)

**Pull request closed without merging**
