### PR TITLE
copycat keyboard

### PR DESCRIPTION
**Pull request by sophia0805**
i renamed the branch and it deleted my pr from last night :(( i swear i turned it in 

Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Hello @sophia0805! I was reviewing your case and noticed that neither of your CAD files has your PCB inside. I can only confirm that your case will work with that. Please add your PCB 3d model to your case so I can ensure everything looks good! Please tell me when you fix that. Thank you very much, @sophia0805, for your cooperation.

**Comment by sophia0805** [comment]
Hey, @Hyatt-B , thank you so much for the feedback! I made some changes, could you check it out? Thank you!

**Comment by Hyatt-B** [comment]
A few more things. It seems as if the USB-C hole is being blocked by the PCB, and also, the PCB seems to be floating. Thank you!

**Comment by sophia0805** [comment]
alright, what about now @Hyatt-B?

**Review by M0HID — APPROVED** [review]
Great work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
