### PR TITLE
Add WafflePad to main

### PR DESCRIPTION
**Pull request by LiveWaffle**
Project
├── CAD
│   ├── top.stl
│   └── bottom.stl
├── Firmware
│   └── firmware.uf2
├── PCB
│   ├── gerber.zip
│   ├── HackPadCase.kicad_pro
│   └── HackPadCase.kicad_sch
└── plate.dxf

### CODE REVIEW

**Review by M0HID — CHANGES_REQUESTED** [review]
Hi there! Great design so far, but right now you haven't correctly wired the encoder switch! It's currently wired into the Matrix so you need to add another row/column, and give it the appropriate diode

**Comment by M0HID** [comment]
Hey - it still looks like you're missing a few connections 

image

**Review by qcoral — CHANGES_REQUESTED** [review]
hey - this is awesome, but I need the case parts exported to differnet files! check hackpad.hackclub.com/submitting

**Review by M0HID — APPROVED** [review]
Nice work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
