### PR TITLE
WinPad

### PR DESCRIPTION
**Pull request by amino47**
My slack is @Amina

Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Review by qcoral — CHANGES_REQUESTED** [review]
This is super close! Could you add a parts count and the screws you want in the BOM? I'll come back around to it

**Comment by amino47** [comment]
Did I do the screws right?

**Review by qcoral — APPROVED** [review]
Good work on the changes! Congrats, you can order your hackpad at:

https://forms.hackclub.com/hackpad

**Comment by amino47** [comment]
Pull request #67 overwrote my pad in the hackpads folder.

**Pull request merged**
