### PR TITLE
JayPad

### PR DESCRIPTION
**Pull request by Jayx2u**
First PCB design I've ever made! Really fun learning everything. More info in the READMEs I've committed.
image
image

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
great work

**Review by defihook — COMMENTED** [review]
great work

**Review by qcoral — APPROVED** [review]
Nice Job on being the SECOND hackpad approved! This one is super clean, love the designs.

Fill out the order form here: https://forms.hackclub.com/hackpad

**Comment by Jayx2u** [comment]
Thank you! One thing to note is I have a gerber zip and a gerber folder. The gerber zip includes the drill files while the gerber folder doesn't.

**Pull request merged**
