### PR TITLE
SimController

### PR DESCRIPTION
**Pull request by opott**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by scooterthedev** [comment]
Hey @opott!

I just looked over your case and it's looking amazing! The only suggestion I will make is if you can put the 2 parts laying flat on the bed vs straight up. It will make the quality way better, especially in the screw holes, and it make it have a lower chance of failure.

**Comment by opott** [comment]
Thank you @scooterthedev! Would Alex just set the way that it prints? I'm not entirely sure how to fix this!

**Comment by scooterthedev** [comment]
Your probably right. In that case, I approve of the case! 

PS - My slack handle is Scooter Y

**Review by qcoral — APPROVED** [review]
PCB looks good to me, consider this approved!

You can fill out this form to get your hackpad: https://forms.hackclub.com/hackpad
Don't forget to add any screws you may need in the additional info section!

**Pull request merged**
