### PR TITLE
Funkypad submission

### PR DESCRIPTION
**Pull request by SmartDude1569**
```
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)
```

I hope you like my submission!

### CODE REVIEW

**Comment by SmartDude1569** [comment]
going to add rp2040 binary soon, just compiling the qmk firmware rn

**Comment by M0HID** [comment]
Nice work! Could you please add your KiCad source files to the PR as well so that I can review them?

**Comment by SmartDude1569** [comment]
i didnt use KiCad to design it, i used EasyEDA

i could try to convert it to KiCad, but im not sure how

**Comment by qcoral** [comment]
That's fine, but there's a chance your PCB won't work since we're not checking it - just double check it if you're unsure. Otherwise, consider this approved! You can order your hackpad here: https://forms.hackclub.com/hackpad

**Pull request merged**
