### PR TITLE
extrapad v1

### PR DESCRIPTION
**Pull request by lacelit684**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

---
Hi, I made a hackerpad that emulates F13-18 for gaming use.

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Your Gerber seems a little messed up, could you fix this?
image

**Comment by MrDomocle** [comment]
image-34
Plot your file as gerbers again with these *exact* settings, zip the files up and replace the gerbers.zip

**Comment by lacelit684** [comment]
> Hey! Your Gerber seems a little messed up, could you fix this? image

Updated gerbers, I went through a midway design change and forgot to do so

**Comment by MrDomocle** [comment]
I approve
My pr: https://github.com/hackclub/hackpad/pull/80

**Review by qcoral — APPROVED** [review]
awesome job on this hackpad!! i love the fact it's from a workshop, that's actually really neat

anyways, you can get your hackpad here: https://forms.hackclub.com/hackpad

have fun!!

**Pull request merged**
