### PR TITLE
GamePad

### PR DESCRIPTION
**Pull request by Sycrosity**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Sycrosity** [comment]
That should be the final version :)

**Comment by Sycrosity** [comment]
Wait I did??

**Comment by Sycrosity** [comment]
Let me add that now

**Comment by Sycrosity** [comment]
to prove I had done it before the deadline [link](https://github.com/hackclub/hackpad/pull/157/commits/29772317e3043b150162f2c28071ababc478dc24)

**Comment by Sycrosity** [comment]
Will re-add this now!

**Comment by Dongathan-Jong** [comment]
Super sick PCB!! Get your hackpad here: https://forms.hackclub.com/hackpad

**Comment by Sycrosity** [comment]
Yay! thank you :)))))

**Comment by Sycrosity** [comment]
My project has since been updated due to an issue with the pin heights: [link](https://github.com/hackclub/hackpad/pull/277)

**Pull request merged**
