### PR TITLE
initial, will continue working

### PR DESCRIPTION
**Pull request by AllTheSquares**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

(need to continue working on this, firmware did not work at all and pad design is not what I intended, but I was rushing)

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Hey, @AllTheSquares! What is the name of your hackpad? Thank you!

**Comment by Hyatt-B** [comment]
Hey, @AllTheSquares. I need your CAD file to be a .step instead of a .3mf. Thank you!

**Comment by AllTheSquares** [comment]
OK so I did the commit adding the name, files, and such but I have no clue what I did.

LMK if I have to do any more changes

**Comment by Hyatt-B** [comment]
This is one of the best I have seen. One last thing. It seems as if your PCB is floating. If I am wrong, please correct me. Thank you!

**Comment by AllTheSquares** [comment]
> This is one of the best I have seen. One last thing. It seems as if your PCB is floating. If I am wrong, please correct me. Thank you!

Haha, thank you :D
I have no clue how to put mounting screws onto the PCB so I decided to do a funnier approach and made it so the case itself would hold it in place.

**Comment by Hyatt-B** [comment]
Okay then. Your CAD looks good to me then. @HyattB.

**Comment by qcoral** [comment]
hey - this pr seems to affect other people's PRs, please fix and reopen a new one!

**Pull request closed without merging**
