### PR TITLE
SlimPad Added

### PR DESCRIPTION
**Pull request by KoKoOogit**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by a3acx — COMMENTED** [review]
Looks good, but I think you should also have a boot.py if your firmware is in KMK. 

-@a3acx

**Comment by KoKoOogit** [comment]
@a3acx  Thanks for reminding. I just added boot.py :)

**Review by qcoral — APPROVED** [review]
awesome design! you can get your hackpad here:

https://forms.hackclub.com/hackpad

**Comment by KoKoOogit** [comment]
@qcoral  Thanks!!!

**Pull request merged**
