### PR TITLE
Soup_Pad

### PR DESCRIPTION
**Pull request by souptik-samanta**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├──case_bot.stl 
│   └──case_top.stl
 |     └── name.stl
|       └── oled_mount.stl
|
├── firmware 
│                   └── code.py
|                    └── boot.py
|                    └── lib\..                       
└── PCB \
    ├── keypad.kicad_sch
    └──keypad.kicad_pro

(The file names do not matter, just the folders)

### CODE REVIEW

**Comment by souptik-samanta** [comment]
@qcoral does this look good

**Comment by souptik-samanta** [comment]
I started my design way back than zrl send the email to everyone 
and you said 150*150 mm^2 was okay and my dimesntion are 150mm*88.9mm

**Comment by souptik-samanta** [comment]
also choose with lead solder

**Comment by souptik-samanta** [comment]
also @qcoral during ordering the pcb from jlc could this thing be changed 
image
to this settings

**Comment by CircuitCyborg** [comment]
The case design needs to be split into separate parts - CircuitCyborg

**Comment by souptik-samanta** [comment]
> The case design needs to be split into separate parts - CircuitCyborg

Its split that present in the production folder please check that once

**Review by qcoral — APPROVED** [review]
awesome PR, consider this approved! 

FIll out this form to get your hackpad: https://forms.hackclub.com/hackpad

**Comment by souptik-samanta** [comment]
Yayyy!!!!

**Pull request merged**
