### PR TITLE
Add Ctrl_pad

### PR DESCRIPTION
**Pull request by Somebud0180**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Super clean design, but the LCD doesn't seem to be fully connected! (see below) if this is a mistake on my end, let me know and you'll be approved :)
image

**Comment by Somebud0180** [comment]
I think I used the wrong footprint for this one, gonna update everything to match with the 4 pin version.

**Comment by Somebud0180** [comment]
Hey, just updated the case files and the PCB! If I missed anything feel free to ask, thanks!

**Comment by Dongathan-Jong** [comment]
Good stuff! Everything looks great. Get your hackpad here: https://forms.hackclub.com/hackpad

**Pull request merged**
