### PR TITLE
Macropad!!!

### PR DESCRIPTION
**Pull request by yashsethu**
This is my macropad, although the instructions on the site were really weird and sometimes differed from each other, idk if something is wrong, please lmk!

### CODE REVIEW

**Comment by opott** [comment]
PCB looks good to me!

**Comment by opott** [comment]
https://github.com/hackclub/OnBoard/pull/703 I approve

**Comment by yashsethu** [comment]
**Please look at my schematic, especially the rotary encoder and OLED**

**Review by qcoral — CHANGES_REQUESTED** [review]
hey! this is awesome, but the case needs to be split into multiple parts so that it can be 3D printed and assembled. I'll come back around soon

**Review by qcoral — APPROVED** [review]
Awesome job on these changes! You can get your hackpad here:

https://forms.hackclub.com/hackpad

have fun!

**Pull request merged**
