### PR TITLE
FuniDogPad

### PR DESCRIPTION
**Pull request by 29cmb**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binaryadd binary

**Comment by 29cmb** [comment]
> add binaryadd binary

A binary for what? I already included a utf2 in the firmware directory

**Review by qcoral — APPROVED** [review]
This is great, but a couple things:
- the case needs to be broken up into multiple, 3d printable STL files
- You need to use the through-hole XIAO footprint
Good luck!

**Review by qcoral — CHANGES_REQUESTED** [review]
meant to request changes, whoops!

**Comment by 29cmb** [comment]
@qcoral For the STL, I'd assume you mean the top and bottom layers respectively to make it not require supports
And for the footprint, I will update the pcb assuming I can find the correct footprint

Thanks!

**Comment by 29cmb** [comment]
If screw holes are absolutely required, give some dimensions and I'll add them. Otherwise I'll probably just get some hot glue and do it myself

**Review by qcoral — APPROVED** [review]
good work! consider this approved, you can order the hackpad here: https://forms.hackclub.com/hackpad

**Pull request merged**
