### PR TITLE
Rowanpad

### PR DESCRIPTION
**Pull request by GearBoxFox**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Comment by GearBoxFox** [comment]
I meant to add to the original PR comment that I'd like a green case, and I would like to assemble the case/PCB myself.

**Comment by cheyao** [comment]
Hey GearBoxFox! I am currently reviewing your pull request and I've found several problems with it.

In the schematic, your schematic for the joystick is not matching with the footprint, and the seed's schematic is the wrong one (It works but oh well)

In the PCB you got a trace here that you ran into a hole:
image
That is 100% not going to work. I recommend running the DRC.

And here, this blue trace that you ran all around that hole could be shortened a lot with one or two vias. Running that close around a hole is generally not a good idea. 
image

And here in your firmware, you should use the GP pin numbers (The gray ones on this picture)
image

Finally for your case, uh well I don't have anything to say. That is a PCB, not a case.

Anyways gl for your submission!

**Comment by GearBoxFox** [comment]
Thank you for reviewing! I'll update the schematic for the XAIO and fix the traces. When I made my schematic, the guide still said to use that schematic + footprint. As for the case, I'll check the .stl files I exported, I only had the case files selected when I exported them so the PCB shouldn't be in them.

**Comment by GearBoxFox** [comment]
I double-checked the PCB submission, DRC initially missed those two errors but found them the second time. As for the CAD file and firmware pins, those had been set properly on my local machine, so I believe Git simply decided to mess with me.

**Review by jpt1729 — APPROVED** [review]
LGTM

https://github.com/hackclub/hackpad/pull/7

**Comment by cheyao** [comment]
LGTM
#4

**Comment by qcoral** [comment]
LGTM

**Pull request merged**
