### PR TITLE
The code might not work, but i tried my best and will fix it when iget the hackpad

### PR DESCRIPTION
**Pull request by RyanBran888**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by jpt1729 — CHANGES_REQUESTED** [review]
Looks good, just a couple of changes. Put your RyansHackPad Folder in the "hackpads" folder with your CASEHACKPAD.step file too. Also rename your dob.md to README.md (and add in case color + PCB color if you care abt that!) besides that looks good!

**Review by jpt1729 — CHANGES_REQUESTED** [review]
Final steps! You are very close

- [ ] can u delete this file pls
https://github.com/RyanBran888/hackpadPLEASEAPROVE/blob/main/CASEHACKPAD.step
- [ ] Put your completed case into your CAD file (PCB should be inside the case)
- [ ] Follow these steps for the production folder then ur good! https://hackpad.hackclub.com/submitting

**Comment by invictus-anic3tus** [comment]
Looks good! My pr: https://www.github.com/hackclub/hackpad/pull/92
I definitely approve 👍

**Comment by souptik-samanta** [comment]
I approve #85

**Comment by MohammedMMC** [comment]
I approve https://github.com/hackclub/hackpad/pull/104
It appears that all the necessary files are included :)

**Comment by scooterthedev** [comment]
I approve. Looks good! #256

**Comment by invictus-anic3tus** [comment]
I approve #92

**Comment by qcoral** [comment]
thanks for all the approvals everyone! this has been approved by me, you can fill out the form here:
https://forms.hackclub.com/hackpad

make sure to include any screws/fasteners if you havent already!

**Comment by souptik-samanta** [comment]
Yayy we all did it

**Pull request merged**
