### PR TITLE
Add mediacontrol

### PR DESCRIPTION
**Pull request by mickeydarrenlau**
Add mediacontrol

### CODE REVIEW

**Comment by mickeydarrenlau** [comment]
All keyswitch hole use mill max hotswao

**Review by defihook — COMMENTED** [review]
add binary

**Comment by mickeydarrenlau** [comment]
It's the circuitpython bin

**Comment by mickeydarrenlau** [comment]
Pcb can't be imported into cad file due to tinkercad limitations 

Used blank plate instead

**Review by qcoral — CHANGES_REQUESTED** [review]
nice job on this hackpad!! this is super close to being approved - I just need to know what screws you want. Could you add that to the BOM?

**Review by qcoral — CHANGES_REQUESTED** [review]
Can you specify a length of screw you're thinking of? otherwise you may get ones that are too long/short

**Review by qcoral — APPROVED** [review]
Good work the changes! This has been approved, you can order your hackpad here:

https://forms.hackclub.com/hackpad

can't wait to see it!

**Pull request merged**
