### PR TITLE
My ithinkiknowwhatimdoing keyboard

### PR DESCRIPTION
**Pull request by nathantsai1**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!
(I hope it works!)

### CODE REVIEW

**Comment by opott** [comment]
Hi,
I've just taken a look at your PCB folder, but the files are in a `.lck` format, so they are unreadable by KiCad. Would it be possible for you to upload the correct files?

**Comment by nathantsai1** [comment]
Hi Opott,

Thank you for reviewing my keyboard project! I have changed the PCB files to be readable by KiCad. Could you please check the requirements again?

-nathan

**Comment by AlphaBeta42** [comment]
Hey @nathantsai1
looking pretty good:
- Schematic looks like you're wiring the columns seperatley for each row? I'd also recommend column labels (like you've used for the rows).
You should consider making it a matrix (which would use 6 io pins instead of 10). But it should work. Efficient use of pins doesn't matter if you're not using those pins for anything else, but it's worth noting for the future. Super easy to do matrixes in firmware, you'd be able to use the kmk minimal example in their [docs](https://github.com/KMKfw/kmk_firmware/blob/main/docs/en/Getting_Started.md).
- With this in mind, I'm not sure about your firmware code, you haven't mentioned the row pins at all... I've never used KMK before though.
- Case looks sweet, nicely done :)

**Comment by nathantsai1** [comment]
Thanks @AlphaBeta42 for your input, I will add columns to my input pins!

--Nathan

**Review by M0HID — APPROVED** [review]
Great work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!!

**Review by M0HID — APPROVED** [review]
Great work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!!

**Pull request merged**
