### PR TITLE
aaryav_pad

### PR DESCRIPTION
**Pull request by aaryavbehl**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Comment by aaryavbehl** [comment]
If it is possible black pcb with white silkscreen would be lovely.

**Review by defihook — COMMENTED** [review]
thanks aaryabehi for your great work

**Review by qcoral — CHANGES_REQUESTED** [review]
This is awesome, but I can't seem to figure out how the case would fit with the rest of the parts.

There's been some updated submission guidelines since you submitted (nice job on that btw!), so if you could just follow the instructions at https://hackpad.hackclub.com/submitting again that should sort out all the issues

Nice work again and sorry for the delay! Going to crunch through all of this

**Comment by aaryavbehl** [comment]
I have made some changes. Let me know if something is still left, and I will fix it immediately. I am using KMK firmware, so it cannot be compiled into a .uf2 file, so I have uploaded the Python code.

For the case, I'm trying to get a bumper case to protect the edges, but the PCB can be viewed from the bottom and top view because it has a lot of details. PLAN B: if this does not work, I will make a handmade wooden case because that is what I originally wanted.

**Comment by aaryavbehl** [comment]
I also have no idea why all the checks have failed :(

**Comment by qcoral** [comment]
So would the case snap-in? or would you have another way of attaching it

**Comment by aaryavbehl** [comment]
Yeh the case is a snap in

**Comment by qcoral** [comment]
I'll approve this for now, let me know how it goes!
https://forms.hackclub.com/hackpad

**Comment by aaryavbehl** [comment]
I filled the form!!

Thank you so much :)

**Comment by aaryavbehl** [comment]
Also can I get it with just the hotswap thing soldered into it ? I would like to solder the rest of the components by myself.

**Pull request merged**
