### PR TITLE
MPad

### PR DESCRIPTION
**Pull request by asmahdi08**
So the macropad's name is MPad. I want all the case models and plate printed in white color. Let's go, finally finished it.

BOM
 - ec11 rotary encoder with switch
 - 16 Switches
 - 16 Keycaps
 - 17 Diodes
 - 1 rotary encoder keycap

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
You havent requested screws in the BOM! Also, please create a readme containing the necessary info. Look at the example attached. https://github.com/hackclub/hackpad/tree/main/hackpads/orpheuspad

**Comment by asmahdi08** [comment]
Really sorry, so silly of me to forget. I will fix it ASAP

**Comment by asmahdi08** [comment]
I think it's good now @Dongathan-Jong

**Comment by regular030** [comment]
The firmware should be called "firmware.uf2", not main.py

**Comment by regular030** [comment]
> > The firmware should be a ".uf2" file. not main.py
> 
> It's a kmk firmware, I guess kmk doesn't need to be compiled.

It required by hackpad to be a .uf2 file
image

**Comment by regular030** [comment]
Also a preview of your case (with the PCB and case tougher)

**Comment by asmahdi08** [comment]
Okay, thanks for letting me know

**Comment by qcoral** [comment]
.py is fine - will update that in the docs, sorry!

**Comment by asmahdi08** [comment]
So, I added .step files for all the case parts separated and one .step file with all the case parts assembled

**Review by qcoral — APPROVED** [review]
Awesome changes, you've been approved!!

Fill out the form here. Good luck!! https://forms.hackclub.com/hackpad

**Comment by asmahdi08** [comment]
Yayyy!

**Pull request merged**
