### PR TITLE
Yashupad

### PR DESCRIPTION
**Pull request by yashu27STA**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by SpeedyGo55 — CHANGES_REQUESTED** [review]
Looking at your PCB i see that the Traces are all quite narrow. Please make then wider.  Especially the GND and VCC Traces. Also you have multiple GND Traces overlapping over some distance. Please fix that.

**Comment by SpeedyGo55** [comment]
> > Looking at your PCB i see that the Traces are all quite narrow. Please make then wider. Especially the GND and VCC Traces. Also you have multiple GND Traces overlapping over some distance. Please fix that.
> 
> Why is that? These are the default settings and even the official tutorial doesn't say anything about changing the track width, and my own approved hackpad uses the default width as well. Is it really necessary?

I dont want to risk it. It would be even better if you used a Ground Plane. It isnt necessary but a requirement to get approved by me

**Comment by MrDomocle** [comment]
I approve
My PR: https://github.com/hackclib/hackpad/pull/80

**Review by M0HID — APPROVED** [review]
Nice work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
