### PR TITLE
One Pad To Rule Them All

### PR DESCRIPTION
**Pull request by ModernGalahad**
Hope this is good...

### CODE REVIEW

**Comment by opott** [comment]
PCB looks good to me!

**Comment by ModernGalahad** [comment]
Hey @scooterthedev!  That's because I'm going to use heat inserts. M3 to be more exact... I got the dimensions for the holes from https://hackpad.hackclub.com/braindump. Thanks for the look over though! Also I just noticed that I put my text upside down lol...
Also thanks @opott !

**Comment by scooterthedev** [comment]
Awesome @ModernGalahad. Using heat inserts is definitely smart. I approve of this!

PS: My slack handle is Scooter Y
[Onboard](https://GitHub.com/hackclub/onboard/pull/531)

**Comment by ModernGalahad** [comment]
Ok updated what was needed.

**Comment by qcoral** [comment]
Awesome job guys! I approve this. You can fill out this form to get your hackpad!

https://forms.hackclub.com/hackpad

**Comment by ModernGalahad** [comment]
Thanks so much!

**Pull request merged**
