### PR TITLE
PenguinPad

### PR DESCRIPTION
**Pull request by penguin-awsome**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by FluxC0** [comment]
LGTM

**Comment by jamdotjar** [comment]
Seems good to me! #79

**Comment by rainnfx** [comment]
Same here, looks great! [#133](https://github.com/hackclub/hackpad/pull/133)

**Comment by qcoral** [comment]
awesome - merged!

fill out the form here: https://forms.hackclub.com/hackpad

**Pull request merged**
