### PR TITLE
Submit DavinciPad

### PR DESCRIPTION
**Pull request by Caelum-hdot264**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by jamdotjar** [comment]
Seems to be good! #79

**Review by M0HID — CHANGES_REQUESTED** [review]
Hey there, the KiCad files are currently empty! If you could fix that then I can review it for you

**Comment by Caelum-hdot264** [comment]
I add the files.

**Comment by Caelum-hdot264** [comment]
so sorry for being so late, apologies.

**Review by M0HID — APPROVED** [review]
Great work on this! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
