### PR TITLE
rabbitpad submission 

### PR DESCRIPTION
**Pull request by information-fiend**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey! Great submission, although your folders aren't put in the right place! check out the orpheuspad example on how to format your folders.

**Comment by information-fiend** [comment]
got it! thx for the feedback

**Comment by information-fiend** [comment]
hey hey! moved some files around, it should be all good now ^^

**Review by M0HID — APPROVED** [review]
Nice work! You can order your Hackpad [here](https://forms.hackclub.com/hackpad)!

**Pull request merged**
