### PR TITLE
SathyPad

### PR DESCRIPTION
**Pull request by a3acx**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by qcoral — CHANGES_REQUESTED** [review]
hey - awesome job, but i'm not sure how the case is supposed to fit together as the plate + pcb are both floating! let me know if im missing something as the step file is empty

**Comment by a3acx** [comment]
@qcoral Will fix asap!

**Comment by Hyatt-B** [comment]
Looks good to me! @HyattB.

**Review by qcoral — APPROVED** [review]
nice job on the changes! you've been approved for hackpad, fill out the form here:

https://forms.hackclub.com/hackpad - make sure to specify any lengths of screws/fasteners you may need!

**Pull request merged**
