### PR TITLE
strixtpad

### PR DESCRIPTION
**Pull request by strixt17**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Screenshot 2024-10-22 at 6 51 18 PM



see those keys

my only concern is that when you have a keycap on there, I may hit the sides, but idk without the keycaps

**Comment by Hyatt-B** [comment]
Since you are okay with that, your CAD looks good. @Hyatt B.

**Comment by Dongathan-Jong** [comment]
Hey! Could you please split your case up into different parts for us to print? Also, I see screw holes. You should add screws to your BOM!

**Comment by M0HID** [comment]
Hey there - it looks like there are a lot of unnecessary file modifications in this PR. Please could you create a new PR with only the specific files changed?

**Pull request closed without merging**
