### PR TITLE
JohnPad

### PR DESCRIPTION
**Pull request by jpt1729**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

I lowkey stole ur firmware code, so if I need to change it lmk.

I am really bad at design so please forgive any trash that you see. If you see anything questionable, please let me know and I will try to fix.

### CODE REVIEW

**Comment by jpt1729** [comment]
Just want to say I am reworking everything!

**Comment by jpt1729** [comment]
Ok I updated my pr request!

**Comment by jpt1729** [comment]
Also if I could get a black or white PCB that would be sick!

**Review by defihook — COMMENTED** [review]
checked thanks

**Review by defihook — COMMENTED** [review]
confirmed

**Review by qcoral — CHANGES_REQUESTED** [review]
This is really cool! Super close to being approved - only problem is that the case isn't very printable, as the overhangs make it really difficult. Could you try designing it to be more 3D-print friendly?

**Comment by jpt1729** [comment]
Fixed!

**Comment by qcoral** [comment]
Nice fix! The case is a little simple, but technically works - congrats on your hackpad!! Fill out the order form here:

https://forms.hackclub.com/hackpad

**Pull request merged**
