### PR TITLE
xriiipad

### PR DESCRIPTION
**Pull request by xriiitox**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Review by qcoral — CHANGES_REQUESTED** [review]
This is super close!! Could you add the specific screws you need in the BOM? I can approve this after

**Comment by xriiitox** [comment]
I'll be honest: I just followed your CAD tutorial and made the screw holes 2.9mm in diameter. I don't know what type of screws to use exactly.

**Comment by qcoral** [comment]
what length do you need? you're looking at m3 screws

**Comment by xriiitox** [comment]
15 or 16 mm should be good

**Review by qcoral — APPROVED** [review]
Thanks for the update. You've been approved for a hackpad, you can order the parts here:

https://forms.hackclub.com/hackpad

Happy hacking!!

**Pull request merged**
