### PR TITLE
nigiriPad

### PR DESCRIPTION
**Pull request by se1yu**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by se1yu** [comment]
Can't figure out how to do the firmware D:

**Comment by se1yu** [comment]
shoutout to taran mittal the goat.

**Comment by opott** [comment]
PCB looks good to me!

**Comment by opott** [comment]
https://github.com/hackclub/OnBoard/pull/703 I approve

**Review by jpt1729 — APPROVED** [review]
I approve 

https://github.com/hackclub/hackpad/pull/7

**Review by qcoral — APPROVED** [review]
I love this thing!!! the design is amazing and I can't wait to see it be made. 

Based on the file, I think you're looking at m3x16mm screws. You can specify that in the form here: https://forms.hackclub.com/hackpad

**Comment by se1yu** [comment]
https://github.com/hackclub/hackpad/pull/261#issuecomment-2430852525

**Pull request merged**
