### PR TITLE
Scooter's Macro Pad

### PR DESCRIPTION
**Pull request by scooterthedev**
This is just PR #194, but I needed to re-make this since a lot of broken stuff happened to the old repo, lol. All the files are the same, just I needed to re-do the PR lol.

-----------------------------------------------------------------------------------------------------------------------------------------------
I believe I have included all the files for my macro board. Please take a look at the README.md for a description of my macro board, the BOM and some notes that I included. Thanks!!!

Side note - I understand that most of the components I chose are SMD, and I am totally fine with soldering them myself.
Side note² - One of my step files in the CAD folder is zipped due to GitHub not allowing files over 100MB and Git LFS is not available for forked repos.

### CODE REVIEW

**Comment by Hyatt-B** [comment]
For your CAD file, you need to submit a .step of all of the parts in one file and assemble how it will be in. Thank you!

**Comment by scooterthedev** [comment]
> For your CAD file, you need to submit a .step of all of the parts in one file and assemble how it will be in. Thank you!
Perfect, thanks! I will do that shortly. Besides for that, does everything else look good?

**Comment by Hyatt-B** [comment]
Yes it does!

**Comment by Hyatt-B** [comment]
Tell me when you do that pls.

**Comment by scooterthedev** [comment]
@Hyatt-B I just fixed up the step file!

**Review by qcoral — APPROVED** [review]
whoa. this is a pretty crazy macropad, can't wait to see it be made

you can fill out this form for the hackpad, make sure you include what screws you need in the addtitional info section!

https://forms.hackclub.com/hackpad

**Pull request merged**
