### PR TITLE
MITTAL1

### PR DESCRIPTION
**Pull request by Overlord-Runt**
My Name: Taran Mittal
My Slack Handle: @Taran Mittal
My Life: Non-existant

This is the Mittal1, a macropad I created for the Hackpad event at Hack Club.
The Mittal1 boasts a 3x4 button matrix with a knob to control volume. It also comes with a screen to display whatever images or animations you want.
All over the case you Will be able to find quotes and references to many different animes and youtubers.

I was Inspired to make this type of case after looking at different examples from ScottoKeebs and combing features that I liked. After getting The case done I felt like it was missing something, so then I added all the references as well as the Arceus(pronounced Ar-Koos) ring and team sky badge to the case to decorate.

Probably the hardest challenge I faced doing this project was trying to find proper footprints and models for all the parts on the pcb as lots of the websites were either scams or fakes. Another challenge was learning how to make the pcb and firmware, with a large lack of proper tutorials on the internet, as well as this being my first time making anything similar to this, it was a huge struggle to learn everything from scratch.

I hope you like the design and feel free to use it for your own projects(You better credit me for them though)

Here you can see some images of my case:

A top view:
Screen Shot 2024-10-23 at 10 33 51 am

An angle view:
Screen Shot 2024-10-23 at 10 34 01 am

Some of my references/quotes:
Screen Shot 2024-10-23 at 10 36 22 am
Screen Shot 2024-10-23 at 10 36 07 am
Screen Shot 2024-10-23 at 10 36 39 am

### CODE REVIEW

**Comment by Overlord-Runt** [comment]
i just saw the keycap colour requirement. so can you make them red if it is a bright red and white if it isn't bright

**Comment by M0HID** [comment]
Great work so far! Before I can review it, could you move all your files to the hackpads/ folder as shown in [the submission guidelines](https://hackpad.hackclub.com/submitting)?

**Comment by Overlord-Runt** [comment]
done

**Comment by Overlord-Runt** [comment]
i also changed my page and made it a bit better

**Review by qcoral — APPROVED** [review]
amazing work - consider this approved!!

 you can fill out this form for your hackpad: https://forms.hackclub.com/hackpad
 
 have fun!!

**Comment by Overlord-Runt** [comment]
the person on the order form is my friend that I am sending it to because I will be out of the country

**Pull request merged**
