### PR TITLE
AnishHackPad

### PR DESCRIPTION
**Pull request by AnishLaha-26**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Hello @AnishLaha-26. I was going to review your CAD for your Hack Pad and noticed that you don't have a file that has all of your components in one. When you do that, please put the model of your PCB inside of your case so I can make sure it fits. Also, please add it as a .step file. Thank you!

**Comment by AnishLaha-26** [comment]
> Hello @AnishLaha-26. I was going to review your CAD for your Hack Pad and noticed that you don't have a file that has all of your components in one. When you do that, please put the model of your PCB inside of your case so I can make sure it fits. Also, please add it as a .step file. Thank you!

I have now made the changes thanks!

**Comment by Hyatt-B** [comment]
CAD looks good! @HyattB.

**Review by M0HID — CHANGES_REQUESTED** [review]
Hi there, great work on this but could you move your case files into the CAD / production folder? Right now they're in the root of the repo

**Comment by AnishLaha-26** [comment]
Sorry for that! I have made the changes, they are now in production/cad for .STL files and cad/ contains .STEP

**Review by M0HID — APPROVED** [review]
Nice work! You can go ahead and order your [hackpad](https://forms.hackclub.com/hackpad) here!

**Pull request merged**
