### PR TITLE
Add buildpad

### PR DESCRIPTION
**Pull request by TheScientist101**
Hello,

This is my first time working on any hardware-ish stuff. This took me way longer than it should have because there are many versions that I scrapped (I didn't even push) and because I had to learn how to use KiCad and Fusion360. I initially planned on having two rotary encoders but I decided that IO expansion was a little too difficult to deal with especially to be within the size constraint and without SMD parts (since I am not comfortable soldering them). I also wanted to have Neopixels for the underglow but that never ended up happening because I designed a solution and later realized the need for resistors and decoupling capacitors which I tried adding, but I also later decided that I did not want to solder SMD components. My best solution to still get the RGB effect I wanted was to use these color changing LEDs in my BOM below.

Thanks,
Urjith Mishra

### CODE REVIEW

**Comment by Hyatt-B** [comment]
Hey @TheScientist101! I was reviewing your CAD files and noticed that I can't tell if your case is going to work without having the PCB inside that .step file. Do you have a PCb 3d model and if so, can you please add a new file with the PCB inside of your case? Thank you very much!

**Comment by TheScientist101** [comment]
Hey @Hyatt-B, it seems that Fusion 360 doesn't want to let me export imported meshes with other bodies designed in the app. Do you know any way to do this or would it be ok if I uploaded an F3D file instead?

**Comment by scooterthedev** [comment]
You should be able to export it all as one step file within Fusion. When you open a mesh it opens it in a new window. You need to copy the bodies from the new window ie. Your imported PCB, and paste those bodies into the original file with the case. Then you should have both meshes in one file and exporting should export the whole file with both files in it.

**Comment by TheScientist101** [comment]
Alright, @Hyatt-B and @scooterthedev, I believe this should have fixed the issue if you want to take a look on your end.

**Comment by AverseABFun** [comment]
image
Use normal global labels for these. Otherwise, PCB seems good!

**Comment by TheScientist101** [comment]
@AverseABFun I believe I fixed it now, thanks for the review!

**Review by qcoral — CHANGES_REQUESTED** [review]
hi!! glad to hear how much effort you've put into this this thing. it's super close but

I was looking at your schematic and noticed the LEDs have no resistors. Is this intentional?? If it is, let me know!

**Comment by TheScientist101** [comment]
@qcoral Yep, I believe they should work without resistors, since the ones I want are 3.0-3.4V w/ 20mA.

**Comment by AverseABFun** [comment]
You'll want a 165ohm resistor.
https://www.wolframalpha.com/input?i=Ohm%27s+law+calculator&assumption=%7B%22FS%22%7D+-%3E+%7B%7B%22OhmsLaw%22%2C+%22R%22%7D%2C+%7B%22OhmsLaw%22%2C+%22V%22%7D%2C+%7B%22OhmsLaw%22%2C+%22I%22%7D%7D&assumption=%7B%22F%22%2C+%22OhmsLaw%22%2C+%22I%22%7D+-%3E%2220mA%22&assumption=%7B%22F%22%2C+%22OhmsLaw%22%2C+%22V%22%7D+-%3E%223.3+V%22

**Comment by TheScientist101** [comment]
After doing some more research, I wouldn't need resistors, but I would be safer with 15 ohm resistors so I added those for each LED.

**Review by qcoral — APPROVED** [review]
awesome job on this! glad we sorted out the LEDs - even I wasn't too sure

Anyways, you can fill out this form to get your stuff: https://forms.hackclub.com/hackpad

Have fun!!

**Pull request merged**
