### PR TITLE
add HackPAD

### PR DESCRIPTION
**Pull request by zhixuan2333**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Review by qcoral — CHANGES_REQUESTED** [review]
This is awesome! Super close to being approved, just a couple notes:
- The case parts need to be separated out into different STLs. Right now you have a case, but there's no way to 3D print it to fit.
- I also need the screw lengths in the BOM

Other than that, looks great! I'll come back around to it

**Comment by zhixuan2333** [comment]
> This is awesome! Super close to being approved, just a couple notes:
> 
> * The case parts need to be separated out into different STLs. Right now you have a case, but there's no way to 3D print it to fit.
> * I also need the screw lengths in the BOM
> 
> Other than that, looks great! I'll come back around to it


Thank u for review. I'v updated the files.

**Review by qcoral — APPROVED** [review]
nice work on the changes! consider this approved, you can order your hackpad here:

https://forms.hackclub.com/hackpad

**Review by defihook — COMMENTED** [review]
ce11 encoder

**Pull request merged**
