### PR TITLE
MohaPad

### PR DESCRIPTION
**Pull request by MohammedMMC**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Dongathan-Jong** [comment]
Hey there! Unfortunately, a requirement is to have all 3: case, code, and pcb! Please make your case and I will get you approved!

**Comment by MohammedMMC** [comment]
Done Added... but i am unsure about the sizes i hope it fits. Thanks <3

**Comment by Dongathan-Jong** [comment]
That is fine! I will approve this for now, but if you would like to make a change to your case within the next week, you can reach out to me on slack @Ducc. Create a new PR with your changes and I will update the PR. Get your hackpad here: https://forms.hackclub.com/hackpad

**Comment by MohammedMMC** [comment]
YAY! Thanks so much <3

**Pull request merged**
