### PR TITLE
hackpad-aditya

### PR DESCRIPTION
**Pull request by adityanaravane**
Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
add binary

**Review by qcoral — CHANGES_REQUESTED** [review]
Nice job on this! Super close, just needs to the following changes:
- The case should have a USB-C cutout, otherwise it's not going to have a spot for the usb port to come out of

Good luck!

**Comment by adityanaravane** [comment]
I have just made that change. Thank you!

**Comment by souptik-samanta** [comment]
I approve #85

**Review by qcoral — APPROVED** [review]
Nice job! Make sure to specify any screws/diodes/anything you may have missed in the order form

https://forms.hackclub.com/hackpad

congrats on being approved!!

**Review by defihook — COMMENTED** [review]
good progress

**Pull request merged**
