### PR TITLE
Military Industrial Complex Pad

### PR DESCRIPTION
**Pull request by Myzomi**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Comment by Myzomi** [comment]
Bill of Materials states 1x PCB, but I would still like the other two blank pcbs. Thanks :)

**Comment by jpt1729** [comment]
I approve!

https://github.com/hackclub/hackpad/pull/7

**Comment by cheyao** [comment]
LGTM. Just for the case you need to separate the parts, one file per physical-part, and don't include the PCB. Aka 1 STEP file for the cover, 1 for the case, 1 for the plate etc.

#4

**Comment by cheyao** [comment]
Nvm all is good, didn't see you put the case in the production folder

**Comment by sayhan1610** [comment]
Looks p neat and cool to me. I approve!! 🦆 

#64 

https://github.com/hackclub/hackpad/pull/64

**Review by jpt1729 — APPROVED** [review]
I approve!

https://github.com/hackclub/hackpad/pull/7

**Review by cheyao — APPROVED** [review]

**Comment by qcoral** [comment]
Congrats on being approved! You can get your hackpad here:
https://forms.hackclub.com/hackpad

**Pull request merged**
