### PR TITLE
Yodapad

### PR DESCRIPTION
**Pull request by Yoda-Flash**
Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

### CODE REVIEW

**Review by M0HID — CHANGES_REQUESTED** [review]
Hi! Great design so far but it looks like your PCB file is blank! Could you upload the correct one please so I can review it?

**Comment by cheyao** [comment]
In the STEP file in the CAD folder is just a empty file. 

Can you rename your kicad_pcb and kicad_sch files to have the same name as the kicad_pro file? Or else kicad is having a difficult time recognizing that the pcb and schema are part of the project. And my kicad is having trouble opening your pcb file, so I can't really review it.

This isn't very important but maybe you should add a BOM as a separate file.

The firmware lgtm.

**Comment by BrightTheBackpack** [comment]
the case lgtm, could you just move or copy it to the CAD folder?

**Review by M0HID — CHANGES_REQUESTED** [review]
Hi there! The SMD hotswap sockets you use can't be soldered by Alex unfortunately. Could you update your PR by changing the footprint used or add in your README that you're going to solder everything yourself?

**Review by qcoral — APPROVED** [review]
nice job on this! you can get your hackpad here:
https://forms.hackclub.com/hackpad

so glad we met in-person :)

**Comment by Yoda-Flash** [comment]
Yeah, that was awesome! Thanks for the merge!

**Pull request merged**
